---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/11/14 20:36
---

---@class LobbyWidgetType
LobbyWidgetType = {
    LWT_MainLobby = {
        Name = "MainLobby",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/Lobby/UGC_Lobby_Main_UIBP.UGC_Lobby_Main_UIBP_C',
        Instance = nil,
    },
    LWT_ModeSelect = {
        Name = "ModeSelect",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/Lobby/UGC_ModeSelection_UIBP.UGC_ModeSelection_UIBP_C',
        Instance = nil,
    },
    LWT_ClosePopupsTips = {
        Name = "LWT_ClosePopupsTips",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/Lobby/UGC_ClosePopupsTips_UIBP.UGC_ClosePopupsTips_UIBP_C',
        Instance = nil
    },
    LWT_TalentTree = {
        Name = "LWT_TalentTree",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/TalentTree/TalentTree_Main_UIBP.TalentTree_Main_UIBP_C',
        Instance = nil
    },
    LWT_TalentTreeTip = {
        Name = "LWT_TalentTreeTip",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/TalentTree/Item/TalentTree_Introduce_Add_UIBP.TalentTree_Introduce_Add_UIBP_C',
        Instance = nil
    },
    LWT_TalentTreeTipConfirm = {
        Name = "LWT_TalentTreeTipConfirm",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/TalentTree/Item/TalentTree_Introduce_UIBP.TalentTree_Introduce_UIBP_C',
        Instance = nil
    },
    LWT_ModeDifficultyTip = {
        Name = "LWT_ModeDifficultyTip",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/Lobby/Item/UGC_DifficultyTips_UIBP.UGC_DifficultyTips_UIBP_C',
        Instance = nil
    },
    LWT_TalentTreePopup = {
        Name = "LWT_TalentTreePopup",
        Path = 'Asset/Blueprint/Arts_UI/Lobby/UIBP/TalentTree/TalentTree_Popup_UIBP.TalentTree_Popup_UIBP_C',
        Instance = nil
    },
}


---@class LobbyUtils
LobbyUtils = LobbyUtils or {}


function LobbyUtils.GetWidget(WidgetType)
    -- lookup LobbyWidgetType in WidgetType
    if WidgetType and WidgetType.Name then
        for _, v in pairs(LobbyWidgetType) do
            if v == WidgetType then
                if WidgetType.Instance then
                    return WidgetType.Instance
                else
                    if not UGCGameSystem.GameState then return end

                    local LobbyMainUIClass = UGCObjectUtility.LoadClass(UGCGameSystem.GetUGCResourcesFullPath(WidgetType.Path))
                    local PlayerController = UGCGameSystem.GetLocalPlayerController()

                    if not LobbyMainUIClass or not PlayerController then return end

                    WidgetType.Instance = UserWidget.NewWidgetObjectBP(PlayerController, LobbyMainUIClass)
                    WidgetType.Instance:AddToViewport()
                    WidgetType.Instance:SetVisibility(ESlateVisibility.Collapsed)
                    return WidgetType.Instance
                end
            end
        end
    end
end

function LobbyUtils.OpenWidget(WidgetType, ...)
    local Widget = LobbyUtils.GetWidget(WidgetType)

    if Widget.bIsOpened then return end

    -- Widget:AddToViewport()
    Widget:SetVisibility(ESlateVisibility.SelfHitTestInvisible)

    if Widget.OnOpen then
        Widget:OnOpen(select("#", ...) > 0 and ... or {})
    end

    Widget.bIsOpened = true
end

function LobbyUtils.CloseWidget(WidgetType)
    local Widget = LobbyUtils.GetWidget(WidgetType)

    if not Widget.bIsOpened then return end

    -- Widget:RemoveFromViewport()
    Widget:SetVisibility(ESlateVisibility.Collapsed)

    if Widget.OnClose then
        Widget:OnClose()
    end

    Widget.bIsOpened = false
end

function LobbyUtils.UpdateWidget(WidgetType, ...)
    local Widget = LobbyUtils.GetWidget(WidgetType)
    if Widget == nil then
        return
    end

    if not Widget.bIsOpened then return end

    if Widget.OnUpdate then
        ugcprint("[LobbyUtils] UpdateWidget: " .. WidgetType.Name)
        Widget:OnUpdate(select("#", ...) > 0 and ... or {})
    end
end

function LobbyUtils.OpenAndUpdateWidget(WidgetType, ...)
    LobbyUtils.OpenWidget(WidgetType, ...)
    LobbyUtils.UpdateWidget(WidgetType, ...)
end

function LobbyUtils.SetOtherWidgetHidden(bHidden)
    local MainControlPanel = UGCWidgetManagerSystem.GetMainUI()
    if bHidden then
        if MainControlPanel ~= nil then
            UGCWidgetManagerSystem.AddWidgetHiddenLayer(MainControlPanel.MainControlBaseUI)
            UGCWidgetManagerSystem.AddWidgetHiddenLayer(MainControlPanel.ShootingUIPanel)
            UGCWidgetManagerSystem.SetVirtualJoystickVisibility(false);   --隐藏摇杆

            local PC = UGCGameSystem.GetLocalPlayerController()
            if PC then
                UGCWidgetManagerSystem.SetCrosshairVisibility(not bHidden)
            end
        end
    else
        if MainControlPanel ~= nil then
            UGCWidgetManagerSystem.SubWidgetHiddenLayer(MainControlPanel.MainControlBaseUI)
            UGCWidgetManagerSystem.SubWidgetHiddenLayer(MainControlPanel.ShootingUIPanel)
            UGCWidgetManagerSystem.SetVirtualJoystickVisibility(true);   --隐藏摇杆

            local PC = UGCGameSystem.GetLocalPlayerController()
            if PC then
                UGCWidgetManagerSystem.SetCrosshairVisibility(not bHidden)
            end
        end
    end
end

function LobbyUtils.SwitchToLobbyCamera()
    local GetCameraActor = function()
        local CameraClass = UGCObjectUtility.LoadClass("/Script/Engine.Actor")
        local CameraActorName = "Lobby_Camerapawn"
        local CameraActors = UGCObjectUtility.GetAllActorsOfClass(UGCGameSystem.GameState, CameraClass)

        for _, CameraActor in pairs(CameraActors) do
            if UGCObjectUtility.GetObjectName(CameraActor) == CameraActorName then
                return CameraActor
            end
        end
    end

    local PromiseFuture = require("common.PromiseFuture")
    PromiseFuture.New():Set(
            function(P)
                while true do
                    local PlayerController = UGCGameSystem.GetLocalPlayerController()
                    local CameraActor = GetCameraActor()

                    if CameraActor then
                        PlayerController.IsCurrentUsePersistStateView = false
                        PlayerController:SetViewTargetWithBlend(CameraActor)
                        PlayerController.IsCurrentUsePersistStateView = true
                        ugcprint("[LobbyUtils] SwitchToLobbyCamera: true")
                        return
                    else
                        P:Yield()
                    end
                end
            end
    ):AutoResume()
end

function LobbyUtils.ChangeLobbyCharacterMesh(InMeshPath)
    local Class = UGCObjectUtility.LoadClass("/Script/Engine.SkeletalMeshActor")
    local Name = "Male_Fullbody_01"
    local Actors = UGCObjectUtility.GetAllActorsOfClass(UGCGameSystem.GameState, Class)
    ugcprint("Trying ChangeLobbyCharacterMesh: " .. tostring(InMeshPath))

    if #Actors == 0 then
        ugcprint("[LobbyUtils] ChangeLobbyCharacterMesh: Actors:Num() == 0, will retry later")
        UGCTimerUtility.CreateLuaTimer(0.3, function() LobbyUtils.ChangeLobbyCharacterMesh(InMeshPath) end)
        return
    end

    for _, SKMeshActor in ipairs(Actors) do
        local ObjectName = UGCObjectUtility.GetObjectName(SKMeshActor)
        if string.find(ObjectName, Name) then
            if InMeshPath then
                Common.LoadObjectWithSoftPathAsync(InMeshPath, function(SKMesh)
                    SKMeshActor:SetActorHiddenInGame(false)
                    SKMeshActor.SkeletalMeshComponent:SetSkeletalMesh(SKMesh, true)
                    ugcprint("[LobbyUtils] ChangeLobbyCharacterMesh success: " .. tostring(InMeshPath))
                end)
            else
                ugcprint("[LobbyUtils] ChangeLobbyCharacterMesh: nil")
            end
        end
    end

end

function LobbyUtils.GetTrimmedString(InStr, Max)
    local OutStr = InStr
    local Count = FuncUtil.GetStringLength(OutStr)

    if Count > Max then
        OutStr = FuncUtil.SubString(OutStr, 1, Max) .. "..."
    end
    return OutStr or ""
end
