---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/11/14 20:35
---

UGCGameSystem.UGCRequire("Script.Blueprint.Arts_UI.Lobby.LobbyUtils")


---@class LobbyState
LobbyFlowState = {
    LFS_None = "LFS_None",
    LFS_Lobby = "LFS_Lobby",
    LFS_ModeSelect = "LFS_ModeSelect",
    LFS_ExitConfirm = "LFS_ExitPopup",
    LFS_TalentTree = "LFS_TalentTree",
    LFS_HeroSelection = "LFS_HeroSelection",
    LFS_Warehouse = "LFS_Warehouse",
}


---@class LobbyStateSwitcher
local LobbyStateSwitcher = {}


---@class LobbyStateConstraint
local LobbyStateConstraint = {
    [LobbyFlowState.LFS_None] = {
        [LobbyFlowState.LFS_Lobby] = true,
    },
    [LobbyFlowState.LFS_Lobby] = {
        [LobbyFlowState.LFS_ModeSelect] = true,
        [LobbyFlowState.LFS_ExitConfirm] = true,
        [LobbyFlowState.LFS_TalentTree] = true,
        [LobbyFlowState.LFS_HeroSelection] = true,
        [LobbyFlowState.LFS_Warehouse] = true,
    },
    [LobbyFlowState.LFS_ModeSelect] = {
        [LobbyFlowState.LFS_Lobby] = true,
    },
    [LobbyFlowState.LFS_ExitConfirm] = {
        [LobbyFlowState.LFS_Lobby] = true,
    },
    [LobbyFlowState.LFS_TalentTree] = {
        [LobbyFlowState.LFS_Lobby] = true,
    },
    [LobbyFlowState.LFS_HeroSelection] = {
        [LobbyFlowState.LFS_Lobby] = true,
    },
    [LobbyFlowState.LFS_Warehouse] = {
        [LobbyFlowState.LFS_Lobby] = true,
    }
}


local M = LobbyStateSwitcher
local LobbyStateSwitchFuncMap = {
    [LobbyFlowState.LFS_None] = {
        Enter = function() end,
        Leave = function() M:Init() end,
    },
    [LobbyFlowState.LFS_Lobby] = {
        Enter = function() M:Lobby_Enter() end,
        Leave = function() M:Lobby_Leave() end,
    },
    [LobbyFlowState.LFS_ModeSelect] = {
        Enter = function() M:ModeSelect_Enter() end,
        Leave = function() M:ModeSelect_Leave() end,
    },
    [LobbyFlowState.LFS_ExitConfirm] = {
        Enter = function() M:ExitConfirm_Enter() end,
        Leave = function() M:ExitConfirm_Leave() end,
    },
    [LobbyFlowState.LFS_TalentTree] = {
        Enter = function() M:TalentTree_Enter() end,
        Leave = function() M:TalentTree_Leave() end,
    },
    [LobbyFlowState.LFS_HeroSelection] = {
        Enter = function() M:HeroSelection_Enter() end,
        Leave = function() M:HeroSelection_Leave() end,
    },
    [LobbyFlowState.LFS_Warehouse] = {
        Enter = function() M:Warehouse_Enter() end,
        Leave = function() M:Warehouse_Leave() end,
    }
}


local LobbyStateSwitchFuncMapSpec = {
    [LobbyFlowState.LFS_None] = {
        [LobbyFlowState.LFS_Lobby] = function () end,
    }
}


function LobbyStateSwitcher:Init()
    LobbyModel:Init()
end


--------------------------------[[ 状态函数 ]]--------------------------------

function LobbyStateSwitcher:Lobby_Enter()
    ---@see UGC_Lobby_Main_UIBP_C#OnUpdate
    LobbyUtils.OpenAndUpdateWidget(LobbyWidgetType.LWT_MainLobby, { ModeID = LobbyModel:GetCurrentSelectedModeID() })

    LobbyUtils.SwitchToLobbyCamera()
end

function LobbyStateSwitcher:Lobby_Leave()
    local PlayerController = UGCGameSystem.GetLocalPlayerController()
    PlayerController.IsCurrentUsePersistStateView = false
end

function LobbyStateSwitcher:ModeSelect_Enter()
    ---@see UGC_Lobby_Main_UIBP_C#OnClose
    LobbyUtils.CloseWidget(LobbyWidgetType.LWT_MainLobby)
    ---@see UGC_ModeSelection_UIBP_C#OnUpdate
    LobbyUtils.OpenAndUpdateWidget(LobbyWidgetType.LWT_ModeSelect, { FocusedMode = LobbyModel:GetCurrentSelectedModeID() })
end

function LobbyStateSwitcher:ModeSelect_Leave()
    LobbyUtils.CloseWidget(LobbyWidgetType.LWT_ModeSelect)
end

function LobbyStateSwitcher:ExitConfirm_Enter()
    LobbyUtils.OpenWidget(LobbyWidgetType.LWT_ClosePopupsTips)
end

function LobbyStateSwitcher:ExitConfirm_Leave()
    LobbyUtils.CloseWidget(LobbyWidgetType.LWT_ClosePopupsTips)
end

function LobbyStateSwitcher:TalentTree_Enter()
    LobbyUtils.OpenAndUpdateWidget(LobbyWidgetType.LWT_TalentTree)
end

function LobbyStateSwitcher:TalentTree_Leave()
    LobbyUtils.CloseWidget(LobbyWidgetType.LWT_TalentTree)
end

function LobbyStateSwitcher:HeroSelection_Enter()
    LobbyUtils.CloseWidget(LobbyWidgetType.LWT_MainLobby)

    self.OnHeroSelectionClosed = function (self)
        LobbyFlow:Go(LobbyFlowState.LFS_Lobby)
    end

    HeroSelectionManager.OnMainWidgetClosed:Add(self.OnHeroSelectionClosed, self)
    HeroSelectionManager:OpenMainWidget()
end

function LobbyStateSwitcher:HeroSelection_Leave()
    HeroSelectionManager.OnMainWidgetClosed:Remove(self.OnHeroSelectionClosed, self)
end

function LobbyStateSwitcher:Warehouse_Enter()
    self.OnBackpackClosed = function (self)
        LobbyFlow:Go(LobbyFlowState.LFS_Lobby)
    end
    print("[LobbyStateSwitcher:Warehouse_Enter]");

    local BackPackUICloseDelegate = UGCBackpackSystemV2.GetBackpackUIClosedDelegate()

    if BackPackUICloseDelegate then
        BackPackUICloseDelegate:Add(self.OnBackpackClosed, self)
        print("[LobbyStateSwitcher:Warehouse_Enter]");
        UGCBackpackSystemV2.OpenBackpackPanel(3)
    end
end

function LobbyStateSwitcher:Warehouse_Leave()
    local BackPackUICloseDelegate = UGCBackpackSystemV2.GetBackpackUIClosedDelegate()
    if BackPackUICloseDelegate then
        BackPackUICloseDelegate:Remove(self.OnBackpackClosed, self)
    end
end

--------------------------------[[ 状态函数 ]]--------------------------------


function LobbyStateSwitcher:Switch(From, To)
    -- check From/To is valid
    do
        local IsValid = false
        if self:IsValid(From) and self:IsValid(To) then
            IsValid = true
        end

        if not IsValid then
            ugcprint("[LobbyStateSwitcher:Switch] Invalid From/To pram passed to switch state function")
            return
        end
    end

    -- do switch
    ugcprint("[LobbyStateSwitcher:Switch] Leaving: ".. From)
    LobbyStateSwitchFuncMap[From].Leave()

    if LobbyStateSwitchFuncMapSpec[From] and LobbyStateSwitchFuncMapSpec[From][To] then
        LobbyStateSwitchFuncMapSpec[From][To]()
    end

    ugcprint("[LobbyStateSwitcher:Switch] Entering: ".. To)
    LobbyStateSwitchFuncMap[To].Enter()
end

function LobbyStateSwitcher:CanSwitch(From, To)
    return LobbyStateConstraint[From][To] ~= nil
end

function LobbyStateSwitcher:IsValid(InState)
    if InState == nil then
        ugcprint("[LobbyStateSwitcher:IsValid] Invalid InState pram passed to switch state function, InState == nil")
        return false
    end

    if not type(InState) == "string" then
        ugcprint("[LobbyStateSwitcher:IsValid] Invalid InState pram passed to switch state function, type(InState) should be string")
        return false
    end

    for _, v in pairs(LobbyFlowState) do
        if v == InState then
            return true
        end
    end

    ugcprint("[LobbyStateSwitcher:IsValid] Invalid InState pram passed to switch state function, InState not in LobbyState")
    return false
end


return LobbyStateSwitcher