---@class UGCMainUI_C:UserWidgetLayout
---@field MainUI_BackPack_C_0 MainUI_BackPack_C
---@field MainUI_Crawl_C_0 MainUI_Crawl_C
---@field MainUI_Crouch_C_0 MainUI_Crouch_C
---@field MainUI_FireLeft_C_0 MainUI_FireLeft_C
---@field MainUI_FireRight_C_0 MainUI_FireRight_C
---@field MainUI_FirstAid_C_0 MainUI_FirstAid_C
---@field MainUI_FPS_TPS_Switch_C_0 MainUI_FPS_TPS_Switch_C
---@field MainUI_FriendsList_C_0 MainUI_FriendsList_C
---@field MainUI_Joystick_C_0 MainUI_Joystick_C
---@field MainUI_Jump_C_0 MainUI_Jump_C
---@field MainUI_LookAround_C_0 MainUI_LookAround_C
---@field MainUI_Map_C_0 MainUI_Map_C
---@field MainUI_Microphone_Btn_C_0 MainUI_Microphone_Btn_C
---@field MainUI_Pistol_C_0 MainUI_Pistol_C
---@field MainUI_PlayerInfo_C_0 MainUI_PlayerInfo_C
---@field MainUI_Projectile_C_0 MainUI_Projectile_C
---@field MainUI_Rush_C_0 MainUI_Rush_C
---@field MainUI_Setting_Btn_C_0 MainUI_Setting_Btn_C
---@field MainUI_SurviveInfo_C_0 MainUI_SurviveInfo_C
---@field MainUI_Voice_Btn_C_0 MainUI_Voice_Btn_C
---@field MainUI_Weapon1_C_0 MainUI_Weapon1_C
---@field MainUI_Weapon2_C_0 MainUI_Weapon2_C
---@field UGC_GameKillData_Item_UIBP UGC_GameKilldata_Item_UIBP_C
---@field UGC_GF_Currency_Item_UIBP UGC_GF_Currency_Item_UIBP_C
---@field UGC_HeathBar_UIBP UGC_HeathBar_UIBP_C
--Edit Below--
