---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2025/4/18 17:17
---

---@type HeroSelectionViewModel
local VM = UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.HeroSelection.HeroSelectionViewModel")

local TestHeroSelectionViewModel = {}


function TestHeroSelectionViewModel:GetTests()
    return {
        -- { Name = "InitValue", TestFunc = self.TestInitValue },
        { Name = "InitValue", TestFunc = self.TestInitValue_CE31 },
        { Name = "PropertyIsMainUIOpened", TestFunc = self.TestPropertyIsMainUIOpened },
        { Name = "PropertyFocusedHeroID", TestFunc = self.TestPropertyFocusedHeroID },
        { Name = "PropertySelectedHeroID", TestFunc = self.TestPropertySelectedHeroID },
        { Name = "PropertyCanSelect", TestFunc = self.TestPropertyCanSelect },
        { Name = "PropertyHeroList", TestFunc = self.TestPropertyHeroList},
        { Name = "PropertyShowSelectButton", TestFunc = self.TestPropertyShowSelectButton },
        { Name = "PropertyShowBuyButton", TestFunc = self.TestPropertyShowBuyButton },
        { Name = "PropertyHeroPurchaseInfo", TestFunc = self.TestPropertyHeroPurchaseInfo },
        { Name = "PurchaseHeroWithNoCoin", TestFunc = self.TestPurchaseHeroWithNoCoin },
        { Name = "PurchaseAndUnlockHero", TestFunc = self.TestPurchaseAndUnlockHero },
    }
end


function TestHeroSelectionViewModel.TestInitValue(UnitTest)
    UnitTest.AssertEqual(VM.bIsMainUIOpened:get(), false, "bIsMainUIOpened is not false")
    UnitTest.AssertEqual(VM.FocusedHeroID:get(), -1, "FocusedHeroID is not -1")
    UnitTest.AssertEqual(VM.SelectedHeroID:get(), -1, "SelectedHeroID is not -1")
    UnitTest.AssertEqual(VM.bCanSelect:get(), false, "bCanSelect is not false")
    UnitTest.AssertEqual(#VM.HeroSelectionItemDataList:get(), 0, "HeroList is not empty")
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestInitValue_CE31(UnitTest)
    UnitTest.AssertEqual(VM.bIsMainUIOpened:get(), false, "bIsMainUIOpened is not false")
    UnitTest.AssertEqual(VM.FocusedHeroID:get(), -1, "FocusedHeroID is not -1")
    UnitTest.AssertEqual(VM.SelectedHeroID:get(), 101, "SelectedHeroID is not 101")
    UnitTest.AssertEqual(VM.bCanSelect:get(), false, "bCanSelect is not false")
    UnitTest.AssertEqual(#VM.HeroSelectionItemDataList:get(), 0, "HeroList is not empty")
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestPropertyIsMainUIOpened(UnitTest)
    HeroSelectionManager:OpenMainWidget()
    UnitTest.AssertEqual(VM.bIsMainUIOpened:get(), true, "bIsMainUIOpened is not true")
    UGCTimerUtility.CreateLuaTimer(0.1, function()
        HeroSelectionManager:CloseMainWidget()
        UnitTest.Pass()
    end)
end

function TestHeroSelectionViewModel.TestPropertyFocusedHeroID(UnitTest)
    HeroSelectionManager:FocusHero(102)
    UnitTest.AssertEqual(VM.FocusedHeroID:get(), 102, "FocusedHeroID is not 102")
    HeroSelectionManager:FocusHero(101)
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestPropertySelectedHeroID(UnitTest)
    HeroSelectionManager:RequestSelectHero(101)

    UGCTimerUtility.CreateLuaTimer(0.5, function()
        UnitTest.AssertEqual(VM.SelectedHeroID:get(), 101, "SelectedHeroID is not 101")
        HeroSelectionManager:RequestSelectHero(102)
    end)

    UGCTimerUtility.CreateLuaTimer(1, function()
        UnitTest.AssertEqual(VM.SelectedHeroID:get(), 102, "SelectedHeroID is not 102")
        HeroSelectionManager:RequestSelectHero(101)
    end)

    UGCTimerUtility.CreateLuaTimer(1.5, function()
        UnitTest.Pass()
    end)
end

function TestHeroSelectionViewModel.TestPropertyCanSelect(UnitTest)
    HeroSelectionManager:FocusHero(102)
    HeroSelectionManager:RequestSelectHero(101)

    UGCTimerUtility.CreateLuaTimer(0.5, function()
        UnitTest.AssertEqual(VM.bCanSelect:get(), true, "bCanSelect is not true")
        HeroSelectionManager:FocusHero(101)
        UnitTest.AssertEqual(VM.bCanSelect:get(), false, "bCanSelect is not false")
        UnitTest.Pass()
    end)
end

function TestHeroSelectionViewModel.TestPropertyHeroList(UnitTest)
    UnitTest.AssertTrue(next(VM.HeroSelectionItemDataList:get()), "HeroList is not empty")
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestPropertyShowSelectButton(UnitTest)
    HeroSelectionManager:OpenMainWidget()
    VM:executeCommand(VM.FocusCommand, 102)
    UnitTest.AssertEqual(VM.bShowSelectButton:get(), false, "bShowSelectButton is not true")
    VM:executeCommand(VM.FocusCommand, 101)
    HeroSelectionManager:CloseMainWidget()
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestPropertyShowBuyButton(UnitTest)
    HeroSelectionManager:OpenMainWidget()
    VM:executeCommand(VM.FocusCommand, 102)
    UnitTest.AssertEqual(VM.bShowBuyButton:get(), true, "bShowBuyButton is not true")
    VM:executeCommand(VM.FocusCommand, 101)
    HeroSelectionManager:CloseMainWidget()
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestPropertyHeroPurchaseInfo(UnitTest)
    HeroSelectionManager:OpenMainWidget()
    VM:executeCommand(VM.FocusCommand, 102)

    UnitTest.AssertEqual(type(VM.HeroPurchaseInfo:get()), "table", "HeroPurchaseInfo is not a table")
    UnitTest.AssertTrue(VM.HeroPurchaseInfo:get().CoinIcon, "CoinIcon is nil")
    UnitTest.AssertTrue(VM.HeroPurchaseInfo:get().CoinNumber, "CoinNumber is nil")
    UnitTest.AssertTrue(VM.HeroPurchaseInfo:get().CoinNumber_Discount, "CoinNumber_Discount is nil")

    VM:executeCommand(VM.FocusCommand, 101)
    HeroSelectionManager:CloseMainWidget()
    UnitTest.Pass()
end

function TestHeroSelectionViewModel.TestPurchaseHeroWithNoCoin(UnitTest)
    assert(VM.HeroSelectionItemDataList:get()[2].bLocked, "Hero 102 is not locked")

    HeroSelectionManager:OpenMainWidget()
    HeroSelectionManager:PurchaseHero(102)

    UGCTimerUtility.CreateLuaTimer(0.5, function()
        UnitTest.AssertTrue(VM.HeroSelectionItemDataList:get()[2].bLocked, "Hero 102 is not locked")
        UnitTest.AssertEqual(VM.bBuyPopupOpened:get(), false, "bBuyPopupOpened is not false")
        UnitTest.AssertEqual(VM.bCurrencyTipsPopupOpened:get(), true, "bCurrencyTipsPopupOpened is not true")

        VM.bCurrencyTipsPopupOpened:set(false)
        HeroSelectionManager:CloseMainWidget()
        UnitTest.Pass()
    end)
end

function TestHeroSelectionViewModel.TestPurchaseAndUnlockHero(UnitTest)
    assert(VM.HeroSelectionItemDataList:get()[2].bLocked, "Hero 102 is not locked")

    local COM = UGCBlueprintFunctionLibrary.GetGamePartGlobalActor(UGCGameSystem.GameState, "CommodityOperationManager")
    COM:BuyProduct(9000005, 0, 1)
    HeroSelectionManager:OpenMainWidget()
    VM:executeCommand(VM.FocusCommand, 102)
    VM:executeCommand(VM.BuyHeroCommand)

    UGCTimerUtility.CreateLuaTimer(0.5, function()
        HeroSelectionManager:PurchaseHero(102)
    end)

    UGCTimerUtility.CreateLuaTimer(2, function()
        UnitTest.AssertTrue(not VM.HeroSelectionItemDataList:get()[2].bLocked, "Hero 102 is not unlocked")
        UnitTest.AssertEqual(VM.bBuyPopupOpened:get(), false, "bBuyPopupOpened is not false")
        UnitTest.AssertEqual(VM.bCanSelect:get(), true, "bCanSelect is not true")
        UnitTest.AssertEqual(VM.bShowBuyButton:get(), false, "bShowBuyButton is not false")
        UnitTest.AssertEqual(VM.bShowSelectButton:get(), true, "bShowSelectButton is not true")
        HeroSelectionManager:CloseMainWidget()
        ShopV2Manager.MainUI.ItemGetUI:SetVisibility(ESlateVisibility.Collapsed)
        UnitTest.Pass()
    end)
end

return TestHeroSelectionViewModel