---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2025/4/15 11:31
---

local TestHeroSelectionManager = {}

function TestHeroSelectionManager:GetTests()
    return {
        { Name = "InitValue", TestFunc = self.TestInitValue },
        { Name = "RequestSelectHero", TestFunc = self.TestRequestSelectHero },
        { Name = "OnSelectedHeroDeleteTriggered", TestFunc = self.TestOnSelectedHeroDeleteTriggered },
        { Name = "Apply", TestFunc = self.TestApply },
    }
end

function TestHeroSelectionManager.TestInitValue(UnitTest)
    UnitTest.AssertEqual(HeroSelectionManager:GetSelectedHeroID(UGCGameSystem.GetLocalPlayerKey()), 101, "HeroID is not 101")
    UnitTest.Pass()
end

function TestHeroSelectionManager.TestRequestSelectHero(UnitTest)
    HeroSelectionManager:RequestSelectHero(102)

    UGCTimerUtility.CreateLuaTimer(0.5, function()
        local PlayerKey = UGCGameSystem.GetLocalPlayerKey()
        UnitTest.AssertEqual(HeroSelectionManager:GetSelectedHeroID(PlayerKey), 102, "HeroID is not 102")
        HeroSelectionManager:RequestSelectHero(101)
        UGCTimerUtility.CreateLuaTimer(0.5, function() UnitTest.Pass() end)
    end)
end

function TestHeroSelectionManager.TestApply(UnitTest)
    local PlayerKey = UGCGameSystem.GetLocalPlayerKey()

    UnitTest.CallRPC("ApplySelectedHeroData", PlayerKey, 101)

    UGCTimerUtility.CreateLuaTimer(0.5, function()
        local Pawn = UGCGameSystem.GetLocalPlayerPawn()
        if Pawn and Pawn.CoverAllAvatarMeshInfo then
            local MeshName = UGCObjectUtility.GetObjectName(Pawn.CoverAllAvatarMeshInfo.CoverAllCharacterMesh)
            UnitTest.AssertEqual(MeshName, "SK_FullbodyNPC_M_QZ", "MeshName is not SK_FullbodyNPC_M_QZ")
        end
        UnitTest.Pass()
    end)
end

function TestHeroSelectionManager.TestOnSelectedHeroDeleteTriggered(UnitTest)
    TestHeroSelectionManager.NotTriggered = true

    local CB = nil
    CB = function(PlayerKey, HeroID)
        if PlayerKey == UGCGameSystem.GetLocalPlayerKey() then
            HeroSelectionManager.OnHeroSelected:Remove(CB)
            TestHeroSelectionManager.NotTriggered = nil
            UnitTest.AssertEqual(HeroID, 102, "HeroID is not 102")
            HeroSelectionManager:RequestSelectHero(101)
            UGCTimerUtility.CreateLuaTimer(0.5, function() UnitTest.Pass() end)
        end
    end

    HeroSelectionManager.OnHeroSelected:Add(CB)
    HeroSelectionManager:RequestSelectHero(102)

    UGCTimerUtility.CreateLuaTimer(5, function()
        if TestHeroSelectionManager.NotTriggered then
            TestHeroSelectionManager.NotTriggered = nil
            HeroSelectionManager:RequestSelectHero(101)
            UnitTest.UnPass("OnHeroSelected Not Triggered")
        end
    end)
end

return TestHeroSelectionManager