---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2025/4/17 19:05
---

---@class Observable
local Observable = {}
Observable.__index = Observable

---@return Observable
function Observable.new(initialValue)
    local self = setmetatable({}, Observable)
    self.value = initialValue
    self.subscribers = {}
    return self
end

function Observable:subscribe(callback)
    table.insert(self.subscribers, callback)
    return function()
        for i = #self.subscribers, 1, -1 do
            if self.subscribers[i] == callback then
                table.remove(self.subscribers, i)
                break
            end
        end
    end
end

function Observable:set(newValue)
    if self.value ~= newValue then
        self.value = newValue
        for _, callback in ipairs(self.subscribers) do
            callback(newValue)
        end
    end
end

function Observable:get()
    return self.value
end

return Observable