---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2025/4/17 19:05
---

local Observable = UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.HeroSelection.MVVM.Observable")

---@class ViewModel
local ViewModel = {}
ViewModel.__index = ViewModel


function ViewModel.new()
    local self = setmetatable({}, ViewModel)
    self._bindings = {}
    return self
end

---@return Observable
function ViewModel:createProperty(initialValue)
    return Observable.new(initialValue)
end

function ViewModel:bind(Widget, Property, OnUpdate)
    local updateElement = function(Value)
        OnUpdate(Widget, Value)
    end

    local unsubscribe = Property:subscribe(updateElement)
    xpcall(updateElement, LuaXPCallMsgHandler, Property:get())

    table.insert(self._bindings, unsubscribe)
end

function ViewModel:createCommand(executeFunc, canExecuteFunc)
    local cmd = {
        execute = executeFunc,
        canExecute = canExecuteFunc
    }

    return cmd
end

function ViewModel:executeCommand(cmd, ...)
    if cmd.canExecute() then
        cmd.execute(...)
    end
end

return ViewModel