---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/9/12 15:41
---

---@type Delegate
local Delegate = UGCGameSystem.UGCRequire("common.Delegate")


---@type table<int32, int32> @HeroID -> ProductID
local HeroToProductMap = {}


---@class HeroCoinInfo
---@field CoinType int32 @ItemID
---@field CoinIcon string @物品图标
---@field CoinNumber int32 @物品数量
---@field CoinNumber_Discount int32 @折扣后物品价格（nullable）


---@class EPurchaseFailReason
EPurchaseFailReason = {
    Purchased = 0,
    NotEnoughCoin = 1,
    BuyProductResultFailed = 2,
    VirtualItemAddItemResultFailed = 3,
    Unknown = 4,
}


---@class HeroSelectionShopProxy
local HeroSelectionShopProxy = {
    ---@type boolean
    bInitialized = false,

    ---@field OnCoinNumChanged fun()
    OnCoinNumChanged = Delegate.New(),
}

---@type fun()
HeroSelectionShopProxy.OnHeroPurchaseUpdated = UGCDelegateUtility.CreateLuaDelegate()
---@type fun(Reason:EPurchaseFailReason)
HeroSelectionShopProxy.OnHeroPurchaseFailed = UGCDelegateUtility.CreateLuaDelegate()

function HeroSelectionShopProxy:Init(InPlayerController, HeroUIDataArr)
    ugcprint("[HeroSelection] HeroSelectionShopProxy:Init")
    self.PlayerController = InPlayerController

    local RetryTimes = 0
    local MaxRetryTimes = 3
    local RetryInterval = 1

    local function DoInit()
        if self.bInitialized then
            return
        end

        if not self:UpdateDependencies() then
            RetryTimes = RetryTimes + 1
            if RetryTimes <= MaxRetryTimes then
                UGCTimerUtility.CreateLuaTimer(RetryInterval, DoInit, false)
            else
                ugcprint("[HeroSelection] HeroSelectionShopProxy:Init: Failed to init HeroSelectionShopProxy")
            end
            return
        end

        -- 建立英雄到商品的映射
        HeroToProductMap = {}
        for _, HeroUIData in ipairs(HeroUIDataArr) do
            HeroToProductMap[HeroUIData.HeroID] = HeroUIData.ProductID
        end

        -- 注册商店购买结果回调
        self:GetCommodityOperationManager().BuyProductResultDelegate:Add(self.OnBuyProduct, self)
        -- 注册金币余额更新回调
        self:GetVirtualItemManager().OnItemNumUpdatedDelegate:Add(self.OnItemNumUpdated, self)
        -- 注册虚拟物品添加回调
        self:GetVirtualItemManager().AddItemResultDelegate:Add(self.OnVirtualItemAddItemResult, self)

        self.bInitialized = true
    end

    DoInit()
end

function HeroSelectionShopProxy:GetHeroItemID(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    if not ProductID then
        return nil
    end

    local ProductData = self:GetCommodityOperationManager():GetProductData(ProductID) or nil
    if not ProductData then
        print("[HeroSelection] Warning: HeroSelectionShopProxy:GetHeroItemID(): ProductData not found, product ID = " .. tostring(ProductID))
        return nil
    end
    return ProductData.ItemID
end

---查询英雄是否购买
---@param HeroID int32
---@return boolean
function HeroSelectionShopProxy:IsHeroPurchased(HeroID)
    local ItemID = self:GetHeroItemID(HeroID)
    if not ItemID then
        print("[HeroSelection] Warning: HeroSelectionShopProxy:IsHeroPurchased(): HeroItemID not found, hero ID = " .. tostring(HeroID))
        return false
    end
    local PurchasedItemNum = self:GetVirtualItemManager():GetItemNum(ItemID, self.PlayerController)
    if PurchasedItemNum and PurchasedItemNum > 0 then
        return true
    end

    return false
end

---查询购买英雄余额是否充足
---@param HeroID int32
---@return boolean
function HeroSelectionShopProxy:IsHeroCanAfford(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    return self:GetCommodityOperationManager():CanAfford(ProductID, 1, self.PlayerController)
end

---查询购买所需货币类型
---@param HeroID int32
---@return ECurrencyType, int32 @货币物品 ID，（可选）CostID
function HeroSelectionShopProxy:GetCoinType(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    local ProductData = self:GetCommodityOperationManager():GetProductData(ProductID)

    if ProductData and ProductData.CurrencyType then
        -- 需要注意 CostID 不要与 ECurrencyType 中的值重复
        if ProductData.CurrencyType == ECurrencyType.OasisCoin then
            return ECurrencyType.OasisCoin, -1
        elseif ProductData.CurrencyType == ECurrencyType.ActivityCoin then
            return ECurrencyType.ActivityCoin, -1
        elseif ProductData.CurrencyType == ECurrencyType.OtherCoin then
            return ECurrencyType.OtherCoin, ProductData.CostID or -1
        end
    end

    return ECurrencyType.OtherCoin
end

---查询购买所需货币数量
---@param HeroID int32
---@return int32
function HeroSelectionShopProxy:GetCoinNumber(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    local ProductData = self:GetCommodityOperationManager():GetProductData(ProductID)
    return ProductData and ProductData.SellingPrice or 0
end

---查询购买所需货币数量（折扣价）
---@param HeroID int32
---@return int32
function HeroSelectionShopProxy:GetCoinNumberDiscount(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    return UGCCommoditySystem.GetSellingPriceAfterDiscount(ProductID) or 0
end

---查询购买所需货币小图标
---@param HeroID int32
---@return UTexture2D
function HeroSelectionShopProxy:GetCoinIcon(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    local ProductData = self:GetCommodityOperationManager():GetProductData(ProductID)
    local Type = self:GetCoinType(HeroID)
    local IconPath = nil

    local FuncMap = {
        [ECurrencyType.OasisCoin] = function()
            return UGCGameSystem.GetUGCResourcesFullPath("ExtendResource/HeroSelect/OfficialPackage/" .. 'Asset/HeroSelection/Arts_UI/Texture/Icons/Oasis_Icon_Lvzhou.Oasis_Icon_Lvzhou')
        end,
        [ECurrencyType.ActivityCoin] = function()
            return UGCGameSystem.GetUGCResourcesFullPath("ExtendResource/HeroSelect/OfficialPackage/" .. 'Asset/HeroSelection/Arts_UI/Texture/Icons/Oasis_Icon_Qiyuan.Oasis_Icon_Qiyuan')
        end,
        [ECurrencyType.OtherCoin] = function()
            return ProductData and self:GetVirtualItemManager():GetItemData(ProductData.CostID).ItemIcon or nil
        end,
    }

    if Type then
        IconPath = FuncMap[Type]()
    else
        print("[HeroSelection] Warning: HeroSelectionShopProxy:GetCoinIcon(): Type not found, hero ID = " .. tostring(HeroID))
        return nil
    end

    if IconPath then
        return UE.LoadObject(IconPath)
    end

    return nil
end

---查询购买所需货币全部信息
---@param HeroID int32
---@return HeroCoinInfo
function HeroSelectionShopProxy:GetCoinInfo(HeroID)
    return {
        CoinType = self:GetCoinType(HeroID),
        CoinNumber = self:GetCoinNumber(HeroID),
        CoinNumber_Discount = self:GetCoinNumberDiscount(HeroID),
        CoinIcon = self:GetCoinIcon(HeroID),
    }
end

---查询购买所需货币余额
---@param ItemID int32
function HeroSelectionShopProxy:GetRemainCoinNumber(ItemID)
    return self:GetVirtualItemManager() and self:GetVirtualItemManager():GetItemNum(ItemID, self.PlayerController) or 0
end

---打开商城界面
function HeroSelectionShopProxy:OpenShopPanel()
    if ShopV2Manager then
        ShopV2Manager:OpenMainUI()
    else
        ugcprint("[HeroSelection] ShopV2Manager is nil, can't open shop panel. Please check if shop template is currently set up.")
    end
end

---购买英雄
---@param HeroID int32
---@see HeroSelectionShopProxy#OnOnHeroPurchasedSucceeded
---@see HeroSelectionShopProxy#OnHeroPurchaseFailed
function HeroSelectionShopProxy:PurchaseHero(HeroID)
    local ProductID = HeroToProductMap[HeroID]
    local ProductData = self:GetCommodityOperationManager():GetProductData(ProductID)

    if self:IsHeroPurchased(HeroID) then
        print("[HeroSelection] HeroSelectionShopProxy:PurchaseHero(HeroID): Hero already purchased, hero ID = " .. HeroID, true)
        self.OnHeroPurchaseFailed(EPurchaseFailReason.Purchased)
        return
    end

    if not self:IsHeroCanAfford(HeroID) then
        self.OnHeroPurchaseFailed(EPurchaseFailReason.NotEnoughCoin)
        return
    end

    print(string.format("[HeroSelection] HeroSelectionShopProxy:PurchaseHero(HeroID): Sending purchase request, hero ID = %s, product ID = %s, price = %s", HeroID, ProductID, ProductData.SellingPrice), true)
    self:GetCommodityOperationManager():BuyProduct(ProductID, self:GetCoinNumberDiscount(HeroID), 1)
end

function HeroSelectionShopProxy:OnBuyProduct(Result)
    if not Result.bSucceeded then
        self:OnHeroPurchaseFailed(EPurchaseFailReason.BuyProductResultFailed)
    end
end

function HeroSelectionShopProxy:OnItemNumUpdated()
    self.OnHeroPurchaseUpdated()
    self.OnCoinNumChanged()
end

---@param Result VirtualItemAddItemResult
function HeroSelectionShopProxy:OnVirtualItemAddItemResult(Result)
    if not Result.bSucceeded then
        self:OnHeroPurchaseFailed(EPurchaseFailReason.VirtualItemAddItemResultFailed)
    end
end

function HeroSelectionShopProxy:RefreshCachedData()
    ugcprint("[HeroSelection] HeroSelectionShopProxy:RefreshCachedData()")
    return self:UpdateDependencies()
end

function HeroSelectionShopProxy:UpdateDependencies()
    if self:GetCommodityOperationManager() == nil then
        print("[HeroSelection] Warning: HeroSelectionShopProxy:UpdateDependencies(): Failed to update CommodityOperationManager")
        return false
    end
    if self:GetVirtualItemManager() == nil then
        print("[HeroSelection] Warning: HeroSelectionShopProxy:UpdateDependencies(): Failed to update VirtualItemManager")
        return false
    end
    return true
end

---@return CommodityOperationManager
function HeroSelectionShopProxy:GetCommodityOperationManager()
    return UGCBlueprintFunctionLibrary.GetGamePartGlobalActor(UGCGameSystem.GameState, "CommodityOperationManager")
end

---@return VirtualItemManager
function HeroSelectionShopProxy:GetVirtualItemManager()
    return UGCBlueprintFunctionLibrary.GetGamePartGlobalActor(UGCGameSystem.GameState, "VirtualItemManager")
end

return HeroSelectionShopProxy
