---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2024/9/5 15:58
---

UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.Common.Common")
UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.Common.UIManager")


---@type UUserWidget
local UserWidget = UserWidget == nil and nil or UserWidget
local Delegate = UGCGameSystem.UGCRequire("common.Delegate")
---@type HeroSelectionShopProxy
local HeroSelectionShopProxy = UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.HeroSelection.HeroSelectionShopProxy")


---@class HeroSelectionManagerImpl
local HeroSelectionManagerImpl = {
    ---@type BP_HeroSelectionActor_C
    HeroSelectionActor = nil,
    ---@type AvatarPoseComponent_BP_C
    AvatarPoseComponent_BP = nil,
    ---@type UCharacterAvatarComponent
    PlayerAvatar = nil,
    ---@type ASTExtraLobbyCharacter
    LobbyPawn = nil,
    ---@type UGCPlayerController_C
    PlayerController = nil,
    ---@type UGCPlayerPawn_C
    PlayerPawn = nil,
    ---@type string
    PlayerKey = nil,


    ---@type table<number, Hero>
    HeroDataMap = {},
    ---@type HeroUI[]
    HeroUIDataArr = {},
    ---@type HeroAbilityLabel[]
    HeroAbilityLabelDataArr = {},
    ---@type HeroFreeConfig[]
    HeroFreeConfigDataArr = {},
    ---@type table<number, string>
    IdxToHeroIDOrderedMap = {},

    ---@type string
    CurrentFocusedHeroID = -1,

    -- delegates
    OnInitialized = Delegate.New(),
    OnMainWidgetOpened = Delegate.New(),
    OnMainWidgetClosed = Delegate.New(),
    OnHeroFocused = Delegate.New(),
    OnHeroSelected = Delegate.New(),

    -- debug
    HeroFreeDebugData = nil,
}


---------------------------------------------------------------------------------
--- Public API ------------------------------------------------------------------
--- 公共 API 部分，可在其他地方任意使用以控制英雄选择的功能。

function HeroSelectionManagerImpl:GetAllUGCHeroData()
    if self.bInitialized then
        return self.HeroDataMap
    end
end

function HeroSelectionManagerImpl:GetUGCHeroData(HeroID)
    assert(self.bInitialized)

    if HeroID and next(self.HeroDataMap) then
        if self.HeroDataMap[HeroID] then
            return self.HeroDataMap[HeroID]
        elseif self.IdxToHeroIDMap[HeroID] and self.HeroDataMap[self.IdxToHeroIDMap[HeroID]] then
            return self.HeroDataMap[self.IdxToHeroIDMap[HeroID]]
        else
            print("[HeroSelection] Warning: GetUGCHeroData(): param HeroID is invalid.")
        end
    else
        print("[HeroSelection] Warning: GetUGCHeroData(): param HeroID or HeroDataArr is nil.")
    end
end

function HeroSelectionManagerImpl:GetAllUGCHeroUIData()
    if self.bInitialized then
        return self.HeroUIDataArr
    end

    return nil
end

function HeroSelectionManagerImpl:GetUGCHeroUIData(HeroID)
    if self.bInitialized then
        if HeroID and self.HeroUIDataArr then
            for _, v in pairs(self.HeroUIDataArr) do
                if v.HeroID == HeroID then
                    return v
                end
            end
        end
    end

    return nil
end

function HeroSelectionManagerImpl:GetAllUGCHeroAbilityLabelData()
    if self.bInitialized then
        return self.HeroAbilityLabelDataArr
    end

    return nil
end

function HeroSelectionManagerImpl:GetUGCHeroFreeConfigData(HeroID)
    if self.bInitialized then
        if HeroID and self.HeroFreeConfigDataArr then
            for _, v in pairs(self.HeroFreeConfigDataArr) do
                if v.HeroID == HeroID then
                    return v
                end
            end
        end
    end

    return nil
end

function HeroSelectionManagerImpl:GetAllUGCHeroFreeConfigData()
    if self.bInitialized then
        return self.HeroFreeConfigDataArr
    end

    return nil
end

function HeroSelectionManagerImpl:GetDisplayedHeroDataList()
    local Result = {}

    for _, v in pairs(self:GetAllUGCHeroData()) do
        local HeroUIData = self:GetUGCHeroUIData(v.ID)
        local IsShow = HeroUIData and HeroUIData.IsShow or false

        if IsShow then
            table.insert(Result, v)
        end
    end

    if Result then
        table.sort(Result, function(a, b)
            local PriorityA = self:GetUGCHeroUIData(a.ID).SortPriority
            local PriorityB = self:GetUGCHeroUIData(b.ID).SortPriority
            return PriorityA < PriorityB
        end)
    end

    return Result
end

function HeroSelectionManagerImpl:GetFirstAvailableHeroID()
    assert(self.bInitialized)
    ---@param v Hero
    for _, v in pairs(self:GetDisplayedHeroDataList()) do
        if self:IsHeroPermanentFree(v.ID) then
            return v.ID
        end
    end
    return -1
end

function HeroSelectionManagerImpl:GetHeroNum()
    if self.bInitialized then
        local num = 0
        for _, v in pairs(self.HeroDataMap) do
            num = num + 1
        end
        return num
    end

    ugcprint("[HeroSelection] HeroSelectionManagerImpl:GetAllUGCHeroData(): HeroSelectionManagerImpl not initialized.")
    return 0
end

function HeroSelectionManagerImpl:GetHeroPurchaseInfo(HeroID)
    if self.bInitialized then
        return HeroSelectionShopProxy:GetCoinInfo(HeroID)
    end

    return nil
end

function HeroSelectionManagerImpl:GetCurrentFocusedHeroID()
    assert(self.bInitialized and not UGCGameSystem.IsServer())
    return self.CurrentFocusedHeroID
end

function HeroSelectionManagerImpl:GetSelectedHeroID(PlayerKey)
    assert(self.bInitialized)
    return self.HeroSelectionActor:GetSelectedHeroID(PlayerKey)
end

function HeroSelectionManagerImpl:GetUGCHeroAbilityLabelData(HeroID)
    assert(self.bInitialized)

    if not self:GetUGCHeroData(HeroID) then
        return nil
    end

    if self.HeroAbilityLabelDataArr then
        local RetData = {}
        for _, v in pairs(self.HeroAbilityLabelDataArr) do
            if v.HeroID == HeroID then
                table.insert(RetData, v)
            end
        end

        if #RetData > 0 then
            return RetData
        else
            ugcprint(string.format('[HeroSelection] Hero %s has no ability label data.', HeroID))
        end
    end

    return nil
end

function HeroSelectionManagerImpl:GetUGCHeroAbilityLabelDataSize(HeroID)
    if self.bInitialized then
        local TempData = self:GetUGCHeroAbilityLabelData(HeroID)
        return TempData and #TempData or 0
    end
end

function HeroSelectionManagerImpl:IsHeroFree(HeroID)
    if not self.bInitialized then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:IsHeroFree(): HeroSelectionManagerImpl not initialized.")
        return false
    end

    --return self:IsHeroPermanentFree(HeroID) or self:IsHeroTimeLimitedFree(HeroID)
    return true
end

function HeroSelectionManagerImpl:IsHeroTimeLimitedFree(HeroID)
    assert(self.bInitialized)

    -- 付费类型英雄，计算限免逻辑
    if self.HeroFreeDebugData then
        ugcprint(string.format("[HeroSelection] IsHeroTimeLimitedFree: HeroFreeDebugData is enabled, current time is %s.", self.HeroFreeDebugData))
    end

    local Data = self:GetUGCHeroFreeConfigData(HeroID)

    if not Data then
        return false
    end

    -- 1. 获取服务器时间
    -- 2. 转换成 KismetMathLibrary 支持的格式 --> FDateTime
    local ServerTime = UGCGameSystem.GetServerTimeSec()
    local Now = ConvertToFDateTime(ServerTime) or KismetMathLibrary.Now()
    local StartYear, StartMonth, StartDay, StarHour, StartMinute, StartSec = KismetMathLibrary.BreakDateTime(Data.StartDate)
    local NowYear, NowMonth, NowDay, NowHour, NowMinute, NowSec = KismetMathLibrary.BreakDateTime(Now)

    -- 1. 判断是否在有效期内
    if KismetMathLibrary.Less_DateTimeDateTime(Data.StartDate, Now) and KismetMathLibrary.Less_DateTimeDateTime(Now, Data.EndDate) then
        if Data.FreeType == EHeroFreeType.Monthly then
            local TempDateTime
            -- 处理月份：
            if NowDay >= StartDay then
                -- a. NowDay > StartDay 在同月份，无需处理
                TempDateTime = KismetMathLibrary.MakeDateTime(NowYear, NowMonth, StartDay, StarHour, StartMinute, StartSec, 0)
            else
                -- b. NowDay < StartDay 不在同月份，视作跨月，需减去一个月
                local TempMonth = NowMonth - 1  -- [1, 12]
                local TempYear = NowYear
                -- 如果跨年了，就必须减去一年
                if TempMonth == 0 then TempMonth = 12 TempYear = TempYear - 1 end
                TempDateTime = KismetMathLibrary.MakeDateTime(TempYear, TempMonth, StartDay, StarHour, StartMinute, StartSec, 0)
            end
            local TimeSpan = KismetMathLibrary.Subtract_DateTimeDateTime(Now, TempDateTime)
            local DaysOffsetByMonth = KismetMathLibrary.GetTotalDays(TimeSpan)
            ugcprint(string.format("[HeroSelection] IsHeroTimeLimitedFree: Now = %s, TempDateTime = %s, TimeSpan = %s, DaysOffsetByMonth = %f", Now, TempDateTime, TimeSpan, DaysOffsetByMonth))
            if DaysOffsetByMonth > 31 or DaysOffsetByMonth < 0 then
                ugcprint("[HeroSelection] IsHeroTimeLimitedFree: DaysOffsetByMonth is invalid, limited free will not be applied.")
                return false
            end
            if DaysOffsetByMonth > 0 and DaysOffsetByMonth <= Data.DurationDays then
                return true
            end
        elseif Data.FreeType == EHeroFreeType.Weekly then
            local TimeSpan = KismetMathLibrary.Subtract_DateTimeDateTime(Now, Data.StartDate)
            local CycleDays = 7 * Data.CycleNumber
            local DaysOffsetByWeek = KismetMathLibrary.GetTotalDays(TimeSpan) % CycleDays
            ugcprint(string.format("[HeroSelection] IsHeroTimeLimitedFree: Now = %s, TimeSpan = %s, CycleDays = %d, DaysOffsetByWeek = %f", Now, TimeSpan, CycleDays, DaysOffsetByWeek))
            if DaysOffsetByWeek <= Data.DurationDays then
                return true
            end
        elseif Data.FreeType == EHeroFreeType.Daily then
            local TimeSpan = KismetMathLibrary.Subtract_DateTimeDateTime(Now, Data.StartDate)
            local CycleDays = Data.CycleNumber
            local DaysOffsetByNDays = KismetMathLibrary.GetTotalDays(TimeSpan) % CycleDays
            ugcprint(string.format("[HeroSelection] IsHeroTimeLimitedFree: Now = %s, TimeSpan = %s, CycleDays = %d, DaysOffsetByNDays = %f", Now, TimeSpan, CycleDays, DaysOffsetByNDays))
            if DaysOffsetByNDays <= Data.DurationDays then
                return true
            end
        elseif Data.FreeType == EHeroFreeType.Fixed then
            ugcprint("[HeroSelection] IsHeroTimeLimitedFree: Fixed free type")
            return true
        end
    end

    return false
end

function HeroSelectionManagerImpl:IsHeroPermanentFree(HeroID)
    if not self.bInitialized then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:GetAllUGCHeroData(): HeroSelectionManagerImpl not initialized.")
        return false
    end

    -- 免费类型英雄，直接返回 true
    local HeroUIData = self:GetUGCHeroUIData(HeroID)
    if HeroUIData and HeroUIData.IsFree then
        return true
    end

    return false
end

function HeroSelectionManagerImpl:IsHeroLocked(HeroID)
    if not self.bInitialized then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:IsHeroLocked(): HeroSelectionManagerImpl not initialized.")
        return false
    end

    if not HeroID then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:IsHeroLocked(): param HeroID is nil.")
        return false
    end

    -- 英雄是否免费
    if self:IsHeroFree(HeroID) then
        return false
    end

    -- 付费英雄是否已购买
    if HeroSelectionShopProxy:IsHeroPurchased(HeroID) then
        return false
    end

    -- 付费、未购买、非周免英雄
    return true
end

function HeroSelectionManagerImpl:IsHeroPurchased(HeroID)
    if not self.bInitialized then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:IsHeroPurchased(): HeroSelectionManagerImpl not initialized.")
        return false
    end

    return HeroSelectionShopProxy:IsHeroPurchased(HeroID)
end

function HeroSelectionManagerImpl:IsHeroCanAfford(HeroID)
    if not self.bInitialized then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:IsHeroCanSelect(): HeroSelectionManagerImpl not initialized.")
        return false
    end
    return HeroSelectionShopProxy:IsHeroCanAfford(HeroID)
end

function HeroSelectionManagerImpl:FocusHero(HeroID)
    assert(self.bInitialized and not UGCGameSystem.IsServer())
    print("[HeroSelection] HeroSelectionManagerImpl:FocusHero(" .. tostring(HeroID) .. ")")

    if HeroID and self.HeroDataMap and self.HeroDataMap[HeroID] then
        self.CurrentFocusedHeroID = HeroID
        self.OnHeroFocused(HeroID)
    else
        print("[HeroSelection] Warning: HeroSelectionManagerImpl:FocusHero(): param HeroID or HeroDataArr is nil.")
    end
end

function HeroSelectionManagerImpl:RequestSelectHero(HeroID)
    assert(self.bInitialized and not UGCGameSystem.IsServer())
    print("[HeroSelection] RequestSelectHero(" .. tostring(HeroID) .. ")")
    local PC = UGCGameSystem.GetLocalPlayerController()
    local PK = UGCGameSystem.GetLocalPlayerKey()
    UnrealNetwork.CallUnrealRPC(PC, self.HeroSelectionActor, "Server_SelectHero", PK, HeroID)
end

function HeroSelectionManagerImpl:SelectHero(PlayerKey, HeroID)
    assert(self.bInitialized and UGCGameSystem.IsServer() and PlayerKey and HeroID)
    print("[HeroSelection] SelectHero(" .. tostring(PlayerKey) .. ", " .. tostring(HeroID) .. ")")

    self.HeroSelectionActor:SetSelectedHeroID(PlayerKey, HeroID)
    self.OnHeroSelected(PlayerKey, HeroID)
end

function HeroSelectionManagerImpl:SelectCurrentFocusedHero()
    assert(self.bInitialized and not UGCGameSystem.IsServer())
    print("[HeroSelection] SelectCurrentFocusedHero()")
    if self:GetCurrentFocusedHeroID() then
        self:RequestSelectHero(self:GetCurrentFocusedHeroID())
    end
end

function HeroSelectionManagerImpl:IsHeroCanSelect(HeroID)
    assert(self.bInitialized and not UGCGameSystem.IsServer())

    if not HeroID then
        print("[HeroSelection] IsHeroCanSelect(HeroID): param HeroID is nil, will use CurrentFocusedHeroID instead by default.")
    end

    local F = HeroID or self:GetCurrentFocusedHeroID()-- 入参视为当前选中的英雄
    local S = self:GetSelectedHeroID(UGCGameSystem.GetLocalPlayerKey()) -- TODO: Make player key as param

    if F and S then
        -- 选中的英雄和已选择的英雄不同时
        return F ~= S
    elseif F and not S then
        -- 还没选择任何英雄时
        return true
    elseif not F then
        -- 没有选中任何英雄？错误！
        print("[HeroSelection] Warning: IsHeroCanSelect(): No focused hero! Nothing can be selected")
        return false
    end
end

function HeroSelectionManagerImpl:ApplySelectedHeroData(PlayerKey, HeroID)
    assert(self.bInitialized and UGCGameSystem.IsServer() and PlayerKey)
    print("[HeroSelection] ApplySelectedHeroData(" .. tostring(PlayerKey) .. ", " .. tostring(HeroID) .. ")")

    HeroID = HeroID or self:GetSelectedHeroID(PlayerKey)
    if not HeroID or HeroID == -1 then
        print("[HeroSelection] Warning: GetCurrentSelectedHeroID() is nil, will use HeroID instead, this param will be deprecated in the future.")
        return
    end

    local CurrentHeroData = self:GetUGCHeroData(HeroID)
    if not CurrentHeroData then
        print("[HeroSelection] Error: CurrentHeroData is nil, apply failed!")
        return
    end

    local TargetPawn = UGCGameSystem.GetPlayerPawnByPlayerKey(PlayerKey)
    if not TargetPawn then
        print("[HeroSelection] Error: TargetPawn is nil, apply failed!")
        return
    end

    if CurrentHeroData.HeroMeshPath then
        if TargetPawn then
            local Path = UGCObjectUtility.GetPathBySoftObjectPath(CurrentHeroData.HeroMeshPath)
            print("[HeroSelection] Apply Mesh, Path = " .. tostring(Path))
            local NewAvatarMesh = UE.LoadObject(Path)
            TargetPawn:UGCRecoverAvatarMesh()
            UGCTimerUtility.CreateLuaTimer(0.1, function() TargetPawn:UGCSetCharacterMeshCoverAvatarMesh(NewAvatarMesh) end)
        else
            print("[HeroSelection] Warning: Apply Mesh, TargetPawn is nil!")
        end
    end

    local HeroSkills = CurrentHeroData.HeroSkills
    local PersistClientStateComponent = TargetPawn:GetPlayerPersistClientState()
    if HeroSkills and PersistClientStateComponent then
        for _, Skill in ipairs(HeroSkills) do
            print("[HeroSelection] Apply Skill = " .. tostring(Skill))
            if PersistClientStateComponent then
                PersistClientStateComponent:ApplyPersistEffectDataByClass(Skill, -1.0)
            end
        end
    else
        print("[HeroSelection] Warning: Apply skill failed, HeroSkills or PersistClientStateComponent is nil!")
    end

    local HeroBuffs = CurrentHeroData.HeroBuffs
    if HeroBuffs and PersistClientStateComponent then
        for _, Buff in ipairs(HeroBuffs) do
            print("[HeroSelection] Apply Buff = " .. tostring(Buff))
            if PersistClientStateComponent then
                PersistClientStateComponent:ApplyPersistEffectDataByClass(Buff, -1.0)
            end
        end
    else
        print("[HeroSelection] Warning: Apply Buff, HeroBuffs or PersistClientStateComponent is nil!")
    end

    local HeroAttributes = CurrentHeroData.HeroAttributes
    if HeroAttributes then
        for _, Attribute in ipairs(HeroAttributes) do
            print("[HeroSelection] Apply Attribute = " .. tostring(Attribute.GameAttribute.AttributeName))
            UGCAttributeSystem.SetGameAttributeValue(TargetPawn, Attribute.GameAttribute.AttributeName, Attribute.InitialValue)
        end
    else
        print("[HeroSelection] Warning: Apply Attribute failed, HeroAttributes is nil!")
    end
end

--- End Public API --------------------------------------------------------------
---------------------------------------------------------------------------------


function HeroSelectionManagerImpl:Init(InHeroSelectionActor)
    print("[HeroSelection] Init(" .. tostring(InHeroSelectionActor) .. ")")
    if self.bInitialized then
        print("[HeroSelection] Warning: HeroSelectionManagerImpl:Init(): already initialized.")
        return
    end

    if not InHeroSelectionActor then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:init(): HeroSelectionActor is nil, init failed.")
        return
    end

    self.HeroSelectionActor = InHeroSelectionActor
    self:UpdateCachedVariables()

    if not self:InitHeroData() then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:Init(): HeroTable is nil")
        return
    end

    if not self:InitHeroUIData() then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:Init(): InitHeroUIData is nil")
        return
    end

    if not self:InitHeroAbilityLabelData() then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:Init(): InitHeroAbilityLabelData is nil")
        return
    end

    if not self:InitHeroFreeConfigData() then
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:Init(): InitHeroFreeConfigData is nil")
        return
    end

    if not HeroSelectionShopProxy.bInitialized then
        HeroSelectionShopProxy:Init(self.PlayerController, self.HeroUIDataArr)
    end
    self.bInitialized = true
    self.OnInitialized()
end

function HeroSelectionManagerImpl:InitWidget()
    assert(self.bInitialized and not UGCGameSystem.IsServer())
    print("[HeroSelection] InitWidget()")
    local Path = UGCObjectUtility.GetPathBySoftObjectPath(self.HeroSelectionActor.MainWidgetClass)
    UGCWidgetManagerSystem.CreateWidgetAsync(Path, function(Widget)
        Widget:AddToViewport()
        UGCWidgetManagerSystem.HideWidget(Widget)
    end)
end

function HeroSelectionManagerImpl:InitHeroData()
    ugcprint("[HeroSelection] HeroSelectionManagerImpl:InitHeroData()")
    local HeroTable = UGCGameSystem.GetTableData(self.HeroSelectionActor.UGCHeroTable)
    self.HeroDataMap = {}
    self.IdxToHeroIDMap = {}

    local SortIdx = 1

    if HeroTable ~= nil then
        for _, v in pairs(HeroTable) do
            ---@type Hero
            local HeroData = {}

            -- 英雄 ID
            HeroData.ID = v.ID
            -- 英雄名称
            HeroData.Name = v.Name
            -- 英雄描述
            HeroData.Desc = v.Desc
            -- 图标资源引用
            HeroData.Icon = v.Icon
            -- Skill（数组）
            HeroData.HeroSkills = v.HeroSkills:Copy()
            -- Buff（数组）
            HeroData.HeroBuffs = v.HeroBuffs:Copy()
            -- 属性（数组）
            HeroData.HeroAttributes = v.HeroAttributes:Copy()
            -- 骨骼体软引用路径
            HeroData.HeroMeshPath = v.HeroMeshPath:Copy()

            self.HeroDataMap[v.ID] = HeroData
            self.IdxToHeroIDMap[SortIdx] = v.ID

            ugcprint(string.format("[HeroSelection] Init hero data: id = %s, name = %s", v.ID, v.Name))

            SortIdx = SortIdx + 1
        end
        return true
    end
    return false
end

function HeroSelectionManagerImpl:InitHeroUIData()
    ugcprint("[HeroSelection] HeroSelectionManagerImpl:InitHeroUIData()")

    local HeroUIDataTable = UGCGameSystem.GetTableData(self.HeroSelectionActor.UGCHeroUITable)

    if HeroUIDataTable ~= nil then
        for _, v in pairs(HeroUIDataTable) do
            ---@type HeroUI
            local HeroUIData = {}

            HeroUIData.ID = v.ID
            HeroUIData.HeroID = v.HeroID
            HeroUIData.ProductID = v.ProductID
            HeroUIData.SortPriority = v.SortPriority
            HeroUIData.IsShow = v.IsShow
            HeroUIData.IsFree = v.IsFree
            HeroUIData.HeroDetail1 = v.HeroDetail1
            HeroUIData.HeroAbilityLabelIsIcon = v.HeroAbilityLabelIsIcon
            HeroUIData.HeroDetail3 = v.HeroDetail3

            table.insert(self.HeroUIDataArr, HeroUIData)
            ugcprint(string.format("[HeroSelection] Init hero ui data: id = %s, hero = %s, HeroAbilityLabelIsIcon = %s", v.ID, v.HeroID, v.HeroAbilityLabelIsIcon))
        end
        return true
    end
    return false
end

function HeroSelectionManagerImpl:InitHeroAbilityLabelData()
    ugcprint("[HeroSelection] HeroSelectionManagerImpl:InitHeroAbilityLabelData()")
    local HeroAbilityLabelTable = UGCGameSystem.GetTableData(self.HeroSelectionActor.UGCHeroAbilityLabelTable)
    self.HeroAbilityLabelDataArr = {}

    if HeroAbilityLabelTable ~= nil then
        ---@param v HeroAbilityLabel
        for _, v in pairs(HeroAbilityLabelTable) do
            ---@type HeroAbilityLabel
            local HeroAbilityLabelData = {}

            HeroAbilityLabelData.ID = v.ID
            HeroAbilityLabelData.HeroID = v.HeroID
            HeroAbilityLabelData.Name = v.Name
            HeroAbilityLabelData.NameColor = v.NameColor:Copy()
            HeroAbilityLabelData.BackgroundColor = v.BackgroundColor:Copy()
            HeroAbilityLabelData.Icon = v.Icon
            HeroAbilityLabelData.Detail = v.Detail

            table.insert(self.HeroAbilityLabelDataArr, HeroAbilityLabelData)
            ugcprint(string.format("[HeroSelection] Init hero ability label data: id = %s, hero = %s, name = %s", v.ID, v.HeroID, v.Name))
        end
        return true
    end
    return false
end

function HeroSelectionManagerImpl:InitHeroFreeConfigData()
    ugcprint("[HeroSelection] HeroSelectionManagerImpl:InitHeroFreeConfigData()")
    local HeroFreeConfigTable = UGCGameSystem.GetTableData(self.HeroSelectionActor.UGCHeroFreeConfigTable)
    self.HeroFreeConfigDataArr = {}

    if HeroFreeConfigTable ~= nil then
        ---@param v HeroFreeConfig
        for _, v in pairs(HeroFreeConfigTable) do
            ---@type HeroFreeConfig
            local HeroFreeConfigData = {}

            HeroFreeConfigData.ID = v.ID
            HeroFreeConfigData.HeroID = v.HeroID
            HeroFreeConfigData.FreeType = v.FreeType
            HeroFreeConfigData.StartDate = v.StartDate:Copy()
            HeroFreeConfigData.EndDate = v.EndDate:Copy()
            HeroFreeConfigData.CycleNumber = v.CycleNumber
            HeroFreeConfigData.DurationDays = v.DurationDays

            table.insert(self.HeroFreeConfigDataArr, HeroFreeConfigData)
            ugcprint(string.format("[HeroSelection] Init hero free config data: id = %s, hero = %s, type = %d, start = %s, end = %s", v.ID, v.HeroID, v.FreeType, v.StartDate, v.EndDate))
        end
        return true
    end
    return false
end

function HeroSelectionManagerImpl:OpenMainWidget()
    assert(self.bInitialized)
    print("[HeroSelection] OpenMainWidget()")

    -- 设置玩家镜头到展示的英雄模型上
    self.PlayerController:SetViewTargetWithBlend(self.HeroSelectionActor)

    -- 隐藏和平的主界面UI、射击UI，保留设置和聊天按钮
    local MainControlPanel = GameBusinessManager.GetWidgetFromName(ingame, "MainControlPanelTochButton_C");
    if MainControlPanel ~= nil then
        UGCWidgetManagerSystem.AddWidgetHiddenLayer(MainControlPanel.MainControlBaseUI)
        UGCWidgetManagerSystem.AddWidgetHiddenLayer(MainControlPanel.ShootingUIPanel)

        local PC = UGCGameSystem.GetLocalPlayerController()
        PC:SetVirtualJoystickVisibility(false);

        if PC then
            UGCWidgetManagerSystem.SetCrosshairVisibility(false)
        end
    else
        print("[HeroSelection] Warning: CaptureAndHoldUIManager:InitBaseUI MainControlPanel == nil!");
    end

    -- 开启滑动检测
    self:StartDetectTouch()

    -- 调试用，打印目前关键的英雄数据到 log 中
    self:DumpHeroData()

    local PC = UGCGameSystem.GetLocalPlayerController()
    PC.OnTouchInterfaceChangedDelegate:Add(self.OnTouchInterfaceChanged, self)

    self.OnMainWidgetOpened()
end

function HeroSelectionManagerImpl:CloseMainWidget()
    assert(self.bInitialized)
    print("[HeroSelection] CloseMainWidget()")

    -- 还原摄像机到玩家角色
    self.PlayerController:SetViewTargetWithBlend(self.PlayerPawn)

    -- 还原和平的主界面UI、射击UI，保留设置和聊天按钮
    local MainControlPanel = GameBusinessManager.GetWidgetFromName(ingame, "MainControlPanelTochButton_C");
    if MainControlPanel ~= nil then
        UGCWidgetManagerSystem.SubWidgetHiddenLayer(MainControlPanel.MainControlBaseUI)
        UGCWidgetManagerSystem.SubWidgetHiddenLayer(MainControlPanel.ShootingUIPanel)

        local PC = UGCGameSystem.GetLocalPlayerController()
        PC:SetVirtualJoystickVisibility(true);

        if PC then
            UGCWidgetManagerSystem.SetCrosshairVisibility(true)
        end
    else
        print("[HeroSelection] Warning: CaptureAndHoldUIManager:InitBaseUI MainControlPanel == nil!");
    end

    -- 关闭滑动检测
    self:StopDetectTouch()

    local PC = UGCGameSystem.GetLocalPlayerController()
    PC.OnTouchInterfaceChangedDelegate:Remove(self.OnTouchInterfaceChanged, self)

    self.OnMainWidgetClosed()
end

function HeroSelectionManagerImpl:OnTouchInterfaceChanged()
    ugcprint("[HeroSelection] HeroSelectionManagerImpl:OnTouchInterfaceChanged()")
    UGCTimerUtility.CreateLuaTimer(-1, function()
        UGCWidgetManagerSystem.SetVirtualJoystickVisibility(false)
    end)
end

function HeroSelectionManagerImpl:PurchaseHero(HeroID)
    assert(self.bInitialized)
    print("[HeroSelection] HeroSelectionManagerImpl:PurchaseHero(" .. tostring(HeroID) .. ")")
    HeroSelectionShopProxy:PurchaseHero(HeroID)
end

function HeroSelectionManagerImpl:StartDetectTouch()
    self.TimerHandle_CheckTouchMove = UGCTimerUtility.CreateLuaTimer(0.02, function() self:CheckTouchMove() end,true, "CheckTouchMove")
end

function HeroSelectionManagerImpl:StopDetectTouch()
    if self.TimerHandle_CheckTouchMove then
        UGCTimerUtility.RemoveLuaTimer(self.TimerHandle_CheckTouchMove)
    end
end

function HeroSelectionManagerImpl:CheckTouchMove()
    if self.curPos then
        self.prePos = {X = self.curPos.X, Y = self.curPos.Y}
    else
        self.prePos = Client.GetGestureLocation(0):Copy()
    end
    self.curPos = Client.GetGestureLocation(0):Copy()

    if not self.isTouching and (self.curPos.X > 0.01 or self.curPos.Y > 0.01) then
        self.isTouching = true
        self.startPos = {X = self.curPos.X, Y = self.curPos.Y}
        ugcprint("StartPos = "..self.curPos.X.." "..self.curPos.Y)
    end

    if self.isTouching then
        self:CheckIfSlide(self.startPos, self.curPos)
    end
end

function HeroSelectionManagerImpl:CheckIfSlide(startPos, endPos)
    local XOffset = (endPos.X - startPos.X)
    local YOffset = math.abs(endPos.Y - startPos.Y)
    -- 计算滑屏角度
    local atan = math.atan( YOffset, XOffset )
    local deg = math.deg(atan)

    if (self.curPos.X < 0.01 and self.curPos.Y < 0.01) then
        self.isTouching = false
    end

    -- TouchingMoveScaleX：两次检测的 滑动的距离差值 / 屏幕的总长度
    local TouchingMoveScaleX = XOffset / Client.GetViewportSize().X
    if TouchingMoveScaleX ~= 0 and math.abs(TouchingMoveScaleX) < 0.2 then
        if deg < 35 or deg > 145 then
            -- 更新英雄模型方向
            self:UpdateHeroMeshRotation(-TouchingMoveScaleX)
            self.isTouching = false
        end
    end
end

---更新英雄模型方向
---@param Scale number 滑动距离 / 屏幕总宽度
function HeroSelectionManagerImpl:UpdateHeroMeshRotation(Scale)
    local TargetMeshComp = self.HeroSelectionActor.SkeletalMesh
    local TargetRot = Rotator.New(0, Scale * 360, 0) -- todo @ magic number 360
    TargetMeshComp:K2_AddRelativeRotation(TargetRot)
end

-- 刷新 self 中缓存的对象状态
function HeroSelectionManagerImpl:UpdateCachedVariables()
    if self.HeroSelectionActor then

        self.AvatarPoseComponent_BP = self.HeroSelectionActor.AvatarPoseComponent_BP
        if self.AvatarPoseComponent_BP then
            self.LobbyPawn = self.AvatarPoseComponent_BP.LobbyPawn
            self.PlayerAvatar = self.AvatarPoseComponent_BP.PlayerAvatar
        else
            ugcprint("[HeroSelection] HeroSelectionManagerImpl:init(): AvatarPoseComponent_BP is nil")
        end

        self.PlayerController = UGCGameSystem.GetAllPlayerController()[1]
        if self.PlayerController then
            self.PlayerPawn = self.PlayerController:GetCurPawn();
            self.PlayerKey = self.PlayerController:GetInt64PlayerKey();
        else
            ugcprint("[HeroSelection] HeroSelectionManagerImpl:UpdateCacheVariables(): PlayerController is nil")
        end
    else
        ugcprint("[HeroSelection] HeroSelectionManagerImpl:UpdateCacheVariables(): HeroSelectionActor is nil")
    end
end

function HeroSelectionManagerImpl:HasAuthority()
    return self.PlayerController and self.PlayerController:HasAuthority()
end

function HeroSelectionManagerImpl:DumpHeroData()
    ugcprint("---------------------- DumpHeroData ----------------------")
    ---@param HeroData Hero
    for _, HeroData in pairs(self.HeroDataMap) do
        local DumpMsg = {
            HeroData = HeroData,
            HeroUI = self:GetUGCHeroUIData(HeroData.ID),
            HeroAbilityLabel = self:GetUGCHeroAbilityLabelData(HeroData.ID),
            HeroFreeConfig = self:GetUGCHeroFreeConfigData(HeroData.ID),
            NativeFuncResults = {
                IsFree = self:IsHeroFree(HeroData.ID),
                IsHeroPermanentFree = self:IsHeroPermanentFree(HeroData.ID),
                IsIsHeroTimeLimitedFree = self:IsHeroTimeLimitedFree(HeroData.ID),
                IsHeroPurchased = self:IsHeroPurchased(HeroData.ID),
                IsHeroLocked = self:IsHeroLocked(HeroData.ID),
            }
        }
        log_tree(DumpMsg)
    end
    ugcprint("---------------------- DumpHeroData ----------------------")
end

-- 将时间戳转换为 FDateTime
function ConvertToFDateTime(timestamp)
    -- 使用 os.date() 将时间戳转换为表
    local dateTable = os.date("*t", timestamp)

    -- 构造 FDateTime
    local FDateTime = KismetMathLibrary.MakeDateTime(dateTable.year, dateTable.month, dateTable.day, dateTable.hour, dateTable.min, dateTable.sec)

    return FDateTime
end

return HeroSelectionManagerImpl
