---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dluckdu.
--- DateTime: 2025/4/17 19:28
---

---@type ViewModel
local ViewModel = UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.HeroSelection.MVVM.ViewModel")
---@type HeroSelectionShopProxy
local HeroSelectionShopProxy = UGCGameSystem.UGCRequire("ExtendResource.HeroSelect.OfficialPackage." .. "Script.HeroSelection.HeroSelectionShopProxy")

---@class HeroSelectionViewModel:ViewModel
local HeroSelectionViewModel = ViewModel.new()

-- Properties
HeroSelectionViewModel.bIsMainUIOpened = nil
HeroSelectionViewModel.bCanSelect = nil
HeroSelectionViewModel.bShowSelectButton = nil
HeroSelectionViewModel.bShowBuyButton = nil
HeroSelectionViewModel.FocusedHeroID = nil
HeroSelectionViewModel.SelectedHeroID = nil
HeroSelectionViewModel.HeroSelectionItemDataList = nil
HeroSelectionViewModel.bBuyPopupOpened = nil
HeroSelectionViewModel.bCurrencyTipsPopupOpened = nil
HeroSelectionViewModel.HeroPurchaseInfo = nil

-- Commands
HeroSelectionViewModel.FocusCommand = {}
HeroSelectionViewModel.SelectCommand = {}
HeroSelectionViewModel.ReloadHeroListCommand = nil
HeroSelectionViewModel.BuyHeroCommand = nil

function HeroSelectionViewModel:Init()
    assert(not UGCGameSystem.IsServer())
    print("[HeroSelection] ViewModel: Init()")
    if self.Inited then
        print("[HeroSelection] ViewModel: Already inited, will skip init")
        return
    end
    self:InitProperties()
    self:InitPropertyDependencies()
    self:InitCommands()
    self:InitModelBindings()

    self.Inited = true
end

function HeroSelectionViewModel:InitProperties()
    self.bIsMainUIOpened = self:createProperty(false)
    self.SelectedHeroID = self:createProperty(HeroSelectionManager:GetSelectedHeroID(UGCGameSystem.GetLocalPlayerKey()))
    self.FocusedHeroID = self:createProperty(HeroSelectionManager:GetCurrentFocusedHeroID())
    self.bCanSelect = self:createProperty(HeroSelectionManager:IsHeroCanSelect(self.FocusedHeroID:get()))
    self.bShowSelectButton = self:createProperty(false)
    self.bShowBuyButton = self:createProperty(false)
    self.HeroSelectionItemDataList = self:createProperty({})
    self.bBuyPopupOpened = self:createProperty(false)
    self.bCurrencyTipsPopupOpened = self:createProperty(false)
    self.HeroPurchaseInfo = self:createProperty({CoinType = ECurrencyType.OtherCoin, CoinNumber = 0, CoinNumber_Discount = 0, CoinIcon = nil})

    local function ugcprint(Name, Value)
        print("[HeroSelection] ViewModel: Property Updated: " .. tostring(Name) .." = " .. tostring(Value))
    end

    local function log_list(Name, Value)
        for k, v in ipairs(Value) do
            ugcprint(Name .. "[" .. k .. "]", v)
        end
    end

    self.bIsMainUIOpened:subscribe(function(Value) ugcprint("bIsMainUIOpened", Value) end)
    self.bCanSelect:subscribe(function(Value) ugcprint("bCanSelect", Value) end)
    self.bShowSelectButton:subscribe(function(Value) ugcprint("bShowSelectButton", Value) end)
    self.bShowBuyButton:subscribe(function(Value) ugcprint("bShowBuyButton", Value) end)
    self.FocusedHeroID:subscribe(function(Value) ugcprint("FocusedHeroID", Value) end)
    self.SelectedHeroID:subscribe(function(Value) ugcprint("SelectedHeroID", Value) end)
    self.HeroSelectionItemDataList:subscribe(function(Value) log_list("DisplayedHeroDataList", Value) end)
    self.bBuyPopupOpened:subscribe(function(Value) ugcprint("bBuyPopupOpened", Value) end)
    self.bCurrencyTipsPopupOpened:subscribe(function(Value) ugcprint("bCurrencyTipsPopupOpened", Value) end)
    self.HeroPurchaseInfo:subscribe(function(Value) ugcprint("HeroPurchaseInfo", Value) end)
end

function HeroSelectionViewModel:InitCommands()
    self.FocusCommand = self:createCommand(
            function(HeroID)
                HeroSelectionManager:FocusHero(HeroID)
            end,
            function()
                return self.bIsMainUIOpened:get()
            end
    )
    self.SelectCommand = self:createCommand(
            function()
                HeroSelectionManager:RequestSelectHero(self.FocusedHeroID:get())
                self.bCanSelect:set(false)
            end,
            function()
                return self.bIsMainUIOpened:get() and self.bCanSelect:get()
            end
    )
    self.ReloadHeroListCommand = self:createCommand(
            function()
                print("[HeroSelection] ViewModel: ReloadHeroListCommand")
                self.HeroSelectionItemDataList:set(self:GetHeroSelectionItemDataList())
            end,
            function()
                return self.bIsMainUIOpened:get()
            end
    )
    self.BuyHeroCommand = self:createCommand(
            function()
                self.bBuyPopupOpened:set(true)
            end,
            function()
                return self.bIsMainUIOpened:get()
            end
    )
end

function HeroSelectionViewModel:InitModelBindings()
    HeroSelectionManager.OnMainWidgetOpened:Add(function()
        self.bIsMainUIOpened:set(true)
        self:executeCommand(self.ReloadHeroListCommand)
        if self.SelectedHeroID:get() ~= self.FocusedHeroID:get() and self.SelectedHeroID:get() ~= -1 then
            self:executeCommand(self.FocusCommand, self.SelectedHeroID:get())
        end
    end)
    HeroSelectionManager.OnMainWidgetClosed:Add(function()
        self.bIsMainUIOpened:set(false)
    end)
    HeroSelectionManager.OnHeroFocused:Add(function(HeroID)
        self.FocusedHeroID:set(HeroID)
    end)
    HeroSelectionManager.OnHeroSelected:Add(function(PlayerKey, HeroID)
        if PlayerKey == UGCGameSystem.GetLocalPlayerKey() then
            self.SelectedHeroID:set(HeroID)
        end
    end)
    HeroSelectionShopProxy.OnHeroPurchaseUpdated:Add(function()
        print("[HeroSelection] ViewModel: HeroSelectionShopProxy.OnHeroPurchaseUpdated Triggered")
        if HeroSelectionShopProxy:IsHeroPurchased(self.FocusedHeroID:get()) and self.bShowBuyButton:get() then
            self.bBuyPopupOpened:set(false)
            self:executeCommand(self.ReloadHeroListCommand)
            if ShopV2Manager then
                local ItemID = HeroSelectionShopProxy:GetHeroItemID(self.FocusedHeroID:get())
                ShopV2Manager:ShowItemGetPopup(ItemID, 1)
            end
            self.bShowBuyButton:set(false)
            self.bShowSelectButton:set(true)
        end
    end)
    HeroSelectionShopProxy.OnHeroPurchaseFailed:Add(function(Reason)
        print("[HeroSelection] ViewModel: HeroSelectionShopProxy.HeroPurchaseFailed Triggered")
        if Reason == EPurchaseFailReason.NotEnoughCoin then
            self.bBuyPopupOpened:set(false)
            self.bCurrencyTipsPopupOpened:set(true)
        elseif Reason == EPurchaseFailReason.Purchased then
            print("[[HeroSelection] Warning: Hero already purchased")
            UGCWidgetManagerSystem.ShowTipsUI("英雄已经购买")
        else
            if self.bIsMainUIOpened:get() then
                UGCWidgetManagerSystem.ShowTipsUI("未知购买错误")
            end
        end
    end)
end

function HeroSelectionViewModel:InitPropertyDependencies()

    self.SelectedHeroID:subscribe(function(Value)
        self.bCanSelect:set(HeroSelectionManager:IsHeroCanSelect(Value))
        self:executeCommand(self.ReloadHeroListCommand)
    end)

    self.FocusedHeroID:subscribe(function(Value)
        self.bCanSelect:set(HeroSelectionManager:IsHeroCanSelect(Value))

        local bFree = HeroSelectionManager:IsHeroFree(self.FocusedHeroID:get())
        local bPurchased = HeroSelectionManager:IsHeroPurchased(self.FocusedHeroID:get())
        self.bShowSelectButton:set(bFree or bPurchased)

        local bPermanentFree = HeroSelectionManager:IsHeroPermanentFree(self.FocusedHeroID:get())
        self.bShowBuyButton:set(not (bPermanentFree or bPurchased))

        self:executeCommand(self.ReloadHeroListCommand)
    end)

    self.bShowBuyButton:subscribe(function(Value)
        if Value then
            self.HeroPurchaseInfo:set(HeroSelectionManager:GetHeroPurchaseInfo(self.FocusedHeroID:get()))
        end
    end)
end

function HeroSelectionViewModel:GetHeroSelectionItemDataList()
    ---@type Hero[]
    local Result = {}
    for _, v in ipairs(HeroSelectionManager:GetDisplayedHeroDataList()) do
        local Data = {}
        Data.ID = v.ID
        Data.Name = v.Name
        Data.Icon = v.Icon
        Data.bTimeLimitedFree = HeroSelectionManager:IsHeroTimeLimitedFree(v.ID)
        Data.bLocked = HeroSelectionManager:IsHeroLocked(v.ID)
        Data.bFocused = self.FocusedHeroID:get() == v.ID
        Data.bSelected = self.SelectedHeroID:get() == v.ID
        table.insert(Result, Data)
    end
    return Result
end

return HeroSelectionViewModel