---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ASUS.
--- DateTime: 2026/7/8 14:11
---

local BPExtend = function(Instance,PathToSuperBP)
    if Instance.BaseClass == nil then
        Instance.BaseClass = {}
    end
    local superClass = UGCGameSystem.UGCRequire(PathToSuperBP)
    if superClass then
        for k,v in pairs(superClass) do
            if type(v) == "function" then
                Instance.BaseClass[k] = v
            end
            if Instance[k] == nil then
                Instance[k] = v
            end
        end
        --setmetatable(Instance.SuperClass,{__index = superClass})
    end
    return Instance,superClass
end
return BPExtend